// Generated by gencpp from file msl_msgs/MotionInfo.msg
// DO NOT EDIT!


#ifndef MSL_MSGS_MESSAGE_MOTIONINFO_H
#define MSL_MSGS_MESSAGE_MOTIONINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msl_msgs
{
template <class ContainerAllocator>
struct MotionInfo_
{
  typedef MotionInfo_<ContainerAllocator> Type;

  MotionInfo_()
    : angle(0.0)
    , translation(0.0)
    , rotation(0.0)  {
    }
  MotionInfo_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , translation(0.0)
    , rotation(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;

   typedef double _translation_type;
  _translation_type translation;

   typedef double _rotation_type;
  _rotation_type rotation;




  typedef boost::shared_ptr< ::msl_msgs::MotionInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msl_msgs::MotionInfo_<ContainerAllocator> const> ConstPtr;

}; // struct MotionInfo_

typedef ::msl_msgs::MotionInfo_<std::allocator<void> > MotionInfo;

typedef boost::shared_ptr< ::msl_msgs::MotionInfo > MotionInfoPtr;
typedef boost::shared_ptr< ::msl_msgs::MotionInfo const> MotionInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msl_msgs::MotionInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msl_msgs::MotionInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace msl_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'msl_msgs': ['/home/paspartout/cnws/src/cnc-msl/msl_msgs/msg'], 'std_msgs': ['/home/paspartout/dev/pro/ros-void/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/home/paspartout/cnws/src/common_msgs/geometry_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::msl_msgs::MotionInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msl_msgs::MotionInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msl_msgs::MotionInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msl_msgs::MotionInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msl_msgs::MotionInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msl_msgs::MotionInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msl_msgs::MotionInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e734b9058a37842c0bd3937a51c14b8";
  }

  static const char* value(const ::msl_msgs::MotionInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e734b9058a37842ULL;
  static const uint64_t static_value2 = 0xc0bd3937a51c14b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::msl_msgs::MotionInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msl_msgs/MotionInfo";
  }

  static const char* value(const ::msl_msgs::MotionInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msl_msgs::MotionInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle\n\
float64 translation\n\
float64 rotation\n\
";
  }

  static const char* value(const ::msl_msgs::MotionInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msl_msgs::MotionInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.translation);
      stream.next(m.rotation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotionInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msl_msgs::MotionInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msl_msgs::MotionInfo_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "translation: ";
    Printer<double>::stream(s, indent + "  ", v.translation);
    s << indent << "rotation: ";
    Printer<double>::stream(s, indent + "  ", v.rotation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSL_MSGS_MESSAGE_MOTIONINFO_H
